import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
// import Image from "next/image"
import styles from "../styles/Home.module.css"
import MyComponent from "../src/components/MyComponent"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MyComponent />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
